AC_INIT([libglr], [1.0.0], [bugs@example.invalid])
AM_INIT_AUTOMAKE([foreign subdir-objects])
AC_CONFIG_SRCDIR([src/glr/grammar.c])
AC_CONFIG_HEADERS([config.h])
AC_PROG_CC
AM_PROG_AR
LT_INIT

AC_CONFIG_FILES([
 Makefile
 tests/Makefile
 disambstd/Makefile
 rewritelib/Makefile
 bindings/Makefile
])
AC_OUTPUT
