option('build_tests', type: 'boolean', value: true)
option('build_examples', type: 'boolean', value: true)
option('build_disambstd', type: 'boolean', value: true)
option('build_rewritelib', type: 'boolean', value: true)
option('build_cache', type: 'boolean', value: true)
option('build_sharedlib', type: 'boolean', value: false)
option('install_local', type: 'boolean', value: false)
