# glrppConfigVersion.cmake

set(PACKAGE_VERSION "0.1.0")

# Check whether the requested version is compatible
if(PACKAGE_FIND_VERSION)
    if(PACKAGE_FIND_VERSION VERSION_EQUAL PACKAGE_VERSION)
        set(PACKAGE_VERSION_EXACT TRUE)
        set(PACKAGE_VERSION_COMPATIBLE TRUE)
    elseif(PACKAGE_FIND_VERSION VERSION_LESS PACKAGE_VERSION)
        set(PACKAGE_VERSION_COMPATIBLE TRUE)
    else()
        set(PACKAGE_VERSION_COMPATIBLE FALSE)
    endif()
else()
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
endif()
